name: Lint-and-test
on: [pull_request]
jobs:
  call-workflow:
    uses: ISISComputingGroup/reusable-workflows/.github/workflows/linters.yml@main
    with:
      compare-branch: origin/master
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
        version: ['3.10', '3.11', '3.12']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.version }}
      - name: install requirements
        run: pip install -r requirements.txt
      - name: run tests (linux)
        run: python run_all_tests.py
        if: startsWith(matrix.os,'ubuntu')
      - name: run tests (windows)
        run: python run_all_tests.py
        if: startsWith(matrix.os,'windows')
